/**
 * Generates docs/CURRICULUM_COVERAGE.md from the live curriculum + template registry.
 * Run: npm run docs:coverage
 */
import { it } from 'vitest';
import { writeFileSync } from 'node:fs';
import { TEMPLATES, templatesFor } from '../src/engine/registry';
import { CATEGORIES, SUBSKILLS, WORKSHEET_ITEMS } from '../src/curriculum/curriculum';
import { EN_UI } from '../src/i18n/en-ui';
import { STAGES } from '../src/engine/types';

it('writes coverage doc', () => {
  const L: string[] = [];
  L.push('# Curriculum coverage matrix', '');
  L.push('_Generated from the code by `npm run docs:coverage` — do not edit by hand._', '');
  L.push('Legend — **A: observed** in the supplied worksheet photos · **B: prerequisite** skill needed to teach it · **C: extension** proposed beyond the worksheets.', '');
  L.push('## A. Worksheet items observed in the six photographs (pages 10–14, Q1–Q50)', '');
  L.push('| Ref | Worksheet content | Readable | Category | Subskills |', '|---|---|---|---|---|');
  for (const w of WORKSHEET_ITEMS) L.push(`| ${w.ref} | ${w.description} | ${w.readable} | ${w.category} ${EN_UI[`cat.${w.category}`]} | ${w.subskills.join(', ')} |`);
  L.push('', '**Gap recorded:** Q24 shows a "Subtract:" instruction and a row of penguins with options a)4 b)5 c)3 d)2, but the full question text/visual grouping is not legible in the photo. It is not reproduced; generic penguin subtraction within 5 covers the topic.', '');
  L.push('**Worksheet ambiguity handled:** Q31/Q33 ask "How many days are there from 7th July to 27th July". The app never uses this wording; it asks either "how many days pass" (20 — elapsed) or "how many dates, counting both" (21 — inclusive).', '');
  L.push('## Template matrix (14 categories × 3 stages)', '');
  L.push('| Category | Stage | Template | Subskill | Source | Worksheet refs | Verified by |', '|---|---|---|---|---|---|---|');
  for (const c of CATEGORIES) for (const st of STAGES) for (const t of templatesFor(c.id, st)) {
    L.push(`| ${c.id} ${EN_UI[`cat.${c.id}`]} | ${st} | \`${t.id}\` — ${t.title} | ${t.subskill} | ${t.source === 'observed' ? 'A observed' : t.source === 'prerequisite' ? 'B prerequisite' : 'C extension'} | ${(t.worksheetRefs ?? []).join('; ')} | unit: 60 seeds valid · e2e: stage reachable |`);
  }
  L.push('', `Total templates: **${TEMPLATES.length}** (minimum required 126).`, '');
  L.push('## Subskills', '', '| Subskill | Category | Stage | Source | Prerequisites | Gated |', '|---|---|---|---|---|---|');
  for (const s of SUBSKILLS) L.push(`| ${s.id} | ${s.category} | ${s.stage} | ${s.source} | ${(s.prereq ?? []).join(', ')} | ${s.gated ? 'yes (regrouping: unlocked by secure prerequisites or parent setting)' : ''} |`);
  L.push('', '"Verified by" means: every template generated 60 deterministic seeds that passed validation and the pure answer check (tests/unit/generators.test.ts), and every category-stage combination was opened and answered in a real browser (tests/e2e/flows.spec.ts). It does not mean the pedagogy has been evaluated with children.');
  writeFileSync('docs/CURRICULUM_COVERAGE.md', L.join('\n') + '\n');
});

it('writes asset manifest doc', async () => {
  const { SPRITES, CODE_DRAWN } = await import('../src/assets/manifest');
  const L: string[] = ['# Asset manifest', '', '_Generated by `npm run docs:coverage` from `src/assets/sprites.generated.json` and `src/assets/manifest.ts`._', ''];
  L.push('## Provenance', '');
  L.push('- **Raster sprites** were cut automatically (`tools/extract_assets.py`) from the eleven transparent asset sheets supplied in the project root (`ChatGPT Image Sep 27, 2026, 07_19_34 PM-1.png` … `-11.png`). Each object was separated by its alpha channel, cropped, downsized to ≤360 px and saved as WebP with transparency preserved. Whole sheets are never shown.');
  L.push('- **`garden_scenery`** is a decorative crop of the supplied garden-map concept image (`download/ChatGPT_Image_…194655.jpg`) with the logo, text and buttons cut away. It is used only as the welcome-screen backdrop, never as an interactive surface.');
  L.push('- **Not used:** the 22 other images in `download/` are claymation-style concept screens with a *robot* bee, lives and scores, and a Sunday-first calendar. They conflict with the one-consistent-bee and no-lives requirements, so they were used for reference only. The orchard/picnic concept screen (`…194654.jpg` / root `07_01_51 PM.png`) is a layout reference only.');
  L.push('- **Optional generated art** (`tools/generate_art.mjs` → `tools/process_generated.py`, Google Gemini image model): listed below with source `generated: <model> (<date>)`. Prompts are in `tools/art-brief.json`; raw outputs and prompts are kept in `art-generated/raw/`.');
  L.push('- **One bee:** the round storybook bee (`bee`, sheet 1) is the single mascot throughout.');
  L.push('- Mathematical content is never taken from art: all quantities, clocks, calendars, shapes, number lines, ten-frames and base-ten blocks are drawn in code from data.', '');
  L.push('## Raster sprites', '', '| id | file | size | alt text | source sheet | source rect (x,y,w,h) |', '|---|---|---|---|---|---|');
  for (const s of Object.values(SPRITES)) L.push(`| ${s.id} | public/${s.file} | ${s.width}×${s.height} | ${s.alt || '(decorative)'} | ${s.source} | ${s.sourceRect.join(', ')} |`);
  L.push('', 'Anchor: all sprites are drawn centred in their box with `object-fit: contain`. If any sprite fails to load, `Sprite` falls back to a drawn token so gameplay (e.g. counting) never depends on art loading.', '');
  L.push('## Drawn in code', '', '| asset | where | why |', '|---|---|---|');
  for (const c of CODE_DRAWN) L.push(`| ${c.id} | ${c.where} | ${c.why} |`);
  writeFileSync('docs/ASSET_MANIFEST.md', L.join('\n') + '\n');
});
